title: "xolf"
description: "Webagentur aus Baierbrunn"
logo: "xolf-logo.png"

# Your site's domain. E.g: http://yoursite.com
url: ""

parsedown_actived: true

# Comments in posts
comments:
    enabled: false
    disqus_shortname: ""

# Information about author
author:
    name: "Florian Theimer"

    # Social networks
    twitter: "spress_cms"
    github: "https://github.com/spress/Spress"
    bitbucket:
    facebook:
    linkedin:
    gplus:
    youtube:

# Collections
collections:
  posts:
    output: true

  projects:
    output: true

# RSS feed
feed:
    max_item: 10

# Facebook Open Graph
open_graph:
    locale: "en_US"

# Code highlight for <pre> and <code> tags
# Powered by http://highlightjs.org/
code_highlight: true

# Site validation
google_verify: "sSEsk-CnuUIaUV1pT7tT1c5mUYtrIMuj2RhmTKgZd9I"
bing_verify:

# Page menus
top_bar:
    - { name: "+49 (0)89 4117 3607", url: "tel:+498941173607" }
    - { name: Support, url: "/support" }
    - { name: Kontakt, url: "/kontakt" }
    - { name: "Über uns", url: "/ueber-uns" }

# Page menus
top_menu:
    - { name: Startseite, url: "/" }
    - { name: Produkte, url: "/produkte" }
    - { name: Kunden, url: "/kunden" }

bottom_menu:
    - { name: "Go to Spresso theme web", url: "https://github.com/yosymfony/Spress-theme-spresso" }
